# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.CharField(max_length=512)),
                ('email_address', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User'),
        ),
    ]
