# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email_address',
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(default=datetime.datetime(2016, 4, 15, 13, 56, 3, 59872, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
