# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160527_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charts',
            name='y_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
