# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 10:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160527_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDatafiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        # migrations.AddField(
        #     model_name='charts',
        #     name='grouping_by',
        #     field=models.CharField(default=datetime.datetime(2016, 7, 4, 10, 53, 36, 489020, tzinfo=utc), max_length=50),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='customuser',
        #     name='primary_root',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='userdatafiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CustomUser'),
        ),
    ]
